version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kompanion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - KOMPANION_PG_URL=postgresql://postgres:postgres@postgres:5432/kompanion
      - KOMPANION_AUTH_USERNAME=admin
      - KOMPANION_AUTH_PASSWORD=password
      - KOMPANION_BSTORAGE_TYPE=postgres
    volumes:
      - ./app:/app/app

volumes:
  postgres_data: 